[project]
name = "03-pro-and-free-user-track-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents>=0.0.17",
    "pandas>=2.3.0",
    "pyarrow>=20.0.0",
    "streamlit",
]
